image: jangrewe/gitlab-ci-android

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
- build

assembleDebug:
  stage: build
  script:
  - ./gradlew assembleDebug
  - mkdir -p result
  - mv ./build/outputs/apk/debug/kali-nethunter-app-debug.apk result/kali-nethunter-app-debug-$CI_COMMIT_BRANCH.apk
  artifacts:
    paths:
    - ./result/kali-nethunter-app-debug-$CI_COMMIT_BRANCH.apk
    expire_in: 1 week